#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e
cd "$(dirname "$0")/.."
set -x

TELEGRAM_INTERVAL=60000 \
PORT=3222 \
bin/hubot -a telegram -n admiral
